version: '3'
services:
  client:
    image: node:18
    container_name: jobify_client_build
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run build"
    ports:
      - "8081:3000"

  server:
    image: node:18
    container_name: jobify_server_build
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "8082:5000"
