version: '3'
services:
  jobify-app:
    image: node:18
    container_name: jobify-jenkins-container
    working_dir: /app
    volumes:
      - ./Server:/app/Server                        # Server code with node_modules included
      - ./Client/Jobify/dist:/app/Client/Jobify/dist  # React build
    command: sh -c "cd Server && node server.js"
    ports:
      - "8082:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/jobify
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-for-jenkins
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
