version: '3'
services:
  jobify-app:
    image: node:18
    container_name: jobify-jenkins-container
    working_dir: /app
    volumes:
      - ./Server:/app/Server                        # Server code with node_modules included
      - ./Client/Jobify/dist:/app/Client/Jobify/dist  # React build
    command: sh -c "cd Server && node server.js"
    ports:
      - "8082:5000"
